# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            reivan
tagline:          'general-purpose learning agent'
description:      'книги, продуктивность, технологии'
url:              http://reivan.ru/
baseurl:          /

author:
  name:           'reivan'
  url:            https://twitter.com/IvanRevzin

paginate:         5

# Custom vars
# version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde
