# Dependencies
markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            reivan.me
tagline:          You're not living your life correctly
description:      "Мой блок, в котором я пишу о книгах, которые я прочитал."
#description:      "A two-column black theme with a scrolling sidebar. Ideal for sites requiring a master-detail layout, e.g. documentation, cheatsheets, lyrics, notes..."
url:              https://github.com/reivan
baseurl:          /ru/

author:
  name:           'Ivan Revzin'
  url:            https://twitter.com/duckscientist

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/reivan
